{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\nscripts\\test_login.py:11: AssertionError"}, "description": "this test fails", "start": 1620954700773, "stop": 1620954700773, "uuid": "112afba4-4754-4a02-bfcc-df5ea7c3d923", "historyId": "cf9e446d5bf24fa6aea818654b5a1655", "testCaseId": "7301f4affb78a0d2cc73223b98903481", "fullName": "scripts.test_login#test_failure", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "AUTOBVT-I54QPM4"}, {"name": "thread", "value": "6708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}